#!/bin/bash
# Writes the current git commit hash into Configuration/BuildInfo.xcconfig
# so Xcode bakes it into the Info.plist (CommitHash key) at build time.
# Shown in the Settings tab for troubleshooting.
#
# Usage:
#   ./scripts/set-build-info.sh          # auto-detect from git
#   ./scripts/set-build-info.sh abc1234  # explicit hash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$SCRIPT_DIR/.."
XCCONFIG="$REPO_ROOT/Configuration/BuildInfo.xcconfig"

if [ $# -ge 1 ]; then
    HASH="$1"
elif command -v git &>/dev/null && git -C "$REPO_ROOT" rev-parse --short HEAD &>/dev/null; then
    HASH="$(git -C "$REPO_ROOT" rev-parse --short HEAD)"
    # Mark dirty working trees so a troubleshooting hash is never mistaken
    # for a clean build of that commit
    if ! git -C "$REPO_ROOT" diff --quiet HEAD -- 2>/dev/null; then
        HASH="${HASH}-dirty"
    fi
else
    HASH="unknown"
fi

cat > "$XCCONFIG" <<XCEOF
// Auto-generated by scripts/set-build-info.sh — do not edit manually.
COMMIT_HASH = ${HASH}
XCEOF

echo "Set COMMIT_HASH = ${HASH} in Configuration/$(basename "$XCCONFIG")"
